# Basic dependabot.yml file with
# minimum configuration for two package managers

version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    directory: "/frontend"
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: "daily"
    versioning-strategy: lockfile-only

    # enable version updates for pypi
  - package-ecosystem: "pip"
    # look for `requirements.in` in the `backend` directory
    directory: "/backend"
    # check for updates every day (weekdays)
    schedule:
      interval: "daily"
    versioning-strategy: lockfile-only
