# Generated by Django 4.0.4 on 2022-04-29 13:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_comment_content_alter_post_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
    ]
